github.com:
    users:
        TeeJarr:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: TeeJarr
