alter table hotspot.events
    add column event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
;-- -. . -..- - / . -. - .-. -.--
alter table hotspot.events
    add column event_endtime BIGINT,
    add column event_attendees int;
;-- -. . -..- - / . -. - .-. -.--
select *
        from events;
;-- -. . -..- - / . -. - .-. -.--
select *
    from hotspot.events;
;-- -. . -..- - / . -. - .-. -.--
select *
    FROM table ( evemts );
;-- -. . -..- - / . -. - .-. -.--
CREATE TABLE SPRING_SESSION (
                                PRIMARY_ID CHAR(36) NOT NULL,
                                SESSION_ID CHAR(36) NOT NULL,
                                CREATION_TIME BIGINT NOT NULL,
                                LAST_ACCESS_TIME BIGINT NOT NULL,
                                MAX_INACTIVE_INTERVAL INT NOT NULL,
                                EXPIRY_TIME BIGINT NOT NULL,
                                PRINCIPAL_NAME VARCHAR(100),
                                CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
;-- -. . -..- - / . -. - .-. -.--
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
;-- -. . -..- - / . -. - .-. -.--
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
;-- -. . -..- - / . -. - .-. -.--
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
;-- -. . -..- - / . -. - .-. -.--
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
                                           SESSION_PRIMARY_ID CHAR(36) NOT NULL,
                                           ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
                                           ATTRIBUTE_BYTES BYTEA NOT NULL,
                                           CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
                                           CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
                                               REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
;-- -. . -..- - / . -. - .-. -.--
select *
    FROM hotspot.events;
;-- -. . -..- - / . -. - .-. -.--
select *
    FROM hotspot.hotspot.events;
;-- -. . -..- - / . -. - .-. -.--
select *
    FROM events;
;-- -. . -..- - / . -. - .-. -.--
ALTER table events
ADD COLUMN created_at;
;-- -. . -..- - / . -. - .-. -.--
ALTER table events
ADD COLUMN created_at bigint;
;-- -. . -..- - / . -. - .-. -.--
ALTER table user_posts
ADD COLUMN post_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ADD COLUMN username varchar(255),
ADD COLUMN handle varchar(255),
ADD COLUMN created_at bigint,
ADD COLUMN post_text varchar(255);
;-- -. . -..- - / . -. - .-. -.--
SELECT up.username, up.handle, up.created_at, up.created_at
    FROM user_posts up;
;-- -. . -..- - / . -. - .-. -.--
select *
FROM user_posts;