#!/usr/bin/env sh
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
sketchybar --bar display=main

sketchybar --bar position=top 			\
						y_offset=5 							\
						height=40								\
						corner_radius=30				\
						blur_radius=0 					\
						padding_right=20				\
						padding_left=20 				\
						sticky=on		 						\
						shadow=on								\

sketchybar --bar color=0x00000000


##### Changing Defaults #####
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=2	
  padding_right=1
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:14.0"
	background.color=$ITEM_BG_COLOR
	background.corner_radius=25
	background.height=20
	background.drawing=off
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=5
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

##### Adding Right Items #####
source "$ITEM_DIR/clock.sh"
# source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/media.sh"

# source "$CONFIG_DIR/split.sh"
ITEMS=$(sketchybar --query bar | jq -r '.items | .[]')

LEFT_ITEMS=()
RIGHT_ITEMS=()
for item in $ITEMS
do
  POS=$(sketchybar --query ${item} | jq -r '.geometry.position')
  if [ "$POS" = "left" ]; then
    LEFT_ITEMS+=(${item})
  elif [ "$POS" = "right" ]; then
    RIGHT_ITEMS+=(${item})
  fi
done

sketchybar --add bracket left_items ${LEFT_ITEMS[@]} \
           --set left_items background.color=$BAR_COLOR \
                            background.height=39 \
														background.padding_left=30 \

sketchybar --add bracket right_items ${RIGHT_ITEMS[@]} \
           --set right_items background.color=$BAR_COLOR \
                             background.height=39 \
														background.padding_right=10 \

sketchybar --update

echo "sketchybar configuration loaded..."
